# Generated by Django 6.0.3 on 2026-03-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orderimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordermodificationrequest',
            name='order',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='OrderImage',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderModificationRequest',
        ),
    ]
