from django.contrib import admin

from . import models

for model in (
    models.Customer,
    models.CustomerOrder,
    models.Part,
    models.Quote,
    models.QuoteLine,
    models.QuoteStateTransition,
    models.QuoteDiscussionThread,
    models.QuoteComment,
    models.QuoteAttachment,
    models.QuoteVersion,
    models.QuoteCostBreakdown,
    models.DesignSupportRequest,
    models.DesignSupportAttachment,
    models.ManufacturingPlan,
    models.ManufacturingStep,
    models.StepInputMaterial,
    models.StepOutputPart,
    models.StepArtifact,
    models.DesignBlockTemplate,
    models.BOMNode,
    models.Machine,
    models.MachineMaintenanceWindow,
    models.WarehouseLocation,
    models.InventoryItem,
    models.PickList,
    models.PickListLine,
    models.StockMovement,
    models.WorkOrder,
    models.WorkOrderStep,
    models.ScheduledStep,
    models.ResourceEstimate,
    models.QualityReport,
    models.StoredFile,
    models.InAppNotification,
    models.AuditLogEntry,
    models.UserProfile,
    models.PermissionGrant,
):
    admin.site.register(model)
