# Generated by Django 6.0.3 on 2026-03-27 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('steel_grade', models.CharField(max_length=50)),
                ('product_form', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(max_length=100)),
                ('quantity_tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surface_finish', models.CharField(blank=True, max_length=50, null=True)),
                ('heat_treatment', models.BooleanField(default=False)),
                ('ultrasonic_test', models.BooleanField(default=False)),
                ('mill_certificate', models.BooleanField(default=False)),
                ('blueprint_file', models.FileField(blank=True, null=True, upload_to='blueprints/')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('order_received', 'Order Received'), ('raw_materials', 'Raw Materials Preparation'), ('melting', 'Melting & Refining'), ('casting', 'Continuous Casting'), ('rolling', 'Hot/Cold Rolling'), ('finishing', 'Finishing & Inspection'), ('shipping', 'Ready for Shipping'), ('delivered', 'Delivered')], default='order_received', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_delivery', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_references/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='home.order')),
            ],
        ),
    ]
